### ISSUE TITLE
Figure out how to install GTK

### ISSUE THREAD

**Issue by JerryHue** [pbelokon/termionus#1]
Since this is the first time I have to set up something somewhat complex, I would like to file the following things we need to figure out:

- [ ] How to install GTK for Windows
- [ ] How to install GTK for Linux (do we have to install in the case we want to support Linux environments?)
- [ ] How to connect Rust and GTK together. Since GTK is a C/C++ library, Rust would have to access it through a FFI. We would have to research for any possible bindings for GTK in Rust.

To keep PRs simple, let's create an issue for each point when necessary.

**Comment by pbelokon** [comment]
Here is the link that can help with above tasks https://www.gtk.org/docs/language-bindings/rust

**Comment by JerryHue** [comment]
I'm wondering if we should install GTK at all... It is really powerful, which might be too much for us. Should we go with a smaller toolkit?

**Comment by pbelokon** [comment]
I agree with you it is a very big toolkit, I found this blog about [GUI libraries](https://dev.to/davidedelpapa/rust-gui-introduction-a-k-a-the-state-of-rust-gui-libraries-as-of-january-2021-40gl).  We could use [iced](https://crates.io/crates/Iced) since it is cross platform and light weight.

**Comment by pbelokon** [comment]
Closing this issue since we are not going to use GTK.
